yuaanlin/nextjs.tw

styles/globals.css
fixed docs pre overflow, thanks
=> fixed docs pre overflow

pages/docs/getting-started.mdx
=> Feature start

pages/docs/basic-features/layouts.mdx, pages/docs/basic-features/supported-browsers-features.mdx
=> Completed translations

components/Blockquote.tsx, components/Button.tsx, pages/learn/foundations/about-nextjs/index.mdx
about-nextjs > index翻譯
Feature include translation in index of about-nextjs.
=> feat: about-nextjs > index翻譯

components/Quiz.tsx, components/icons/Correct.tsx, components/icons/Incorrect.tsx, styles/globals.css
**Spec:**
- Create components/Quiz
- Create icons/Correct
- Create icons/Incorrect
- Add the style of answer-list counter
- Save the answer to LocalStorage
--- 
**Completed:**
- Create components/Quiz
- Create icons/Correct
- Create icons/Incorrect
- Add the style of answer-list counter
---
**Unfinished:**
- Save the answer to LocalStorage
=> Create quiz component

pages/learn/foundations/from-react-to-nextjs/next-steps.mdx, pages/learn/foundations/how-nextjs-works/next-steps.mdx
=> updated `pages/learn/foundations/from-react-to-nextjs/next-steps.mdx`

pages/docs/basic-features/data-fetching/get-static-props.mdx
Translate `/docs/basic-features/data-fetching/get-static-props`
=> Translate `/docs/basic-features/data-fetching/get-static-props`

components/Layout/LearnLayout.tsx, components/LearnRoutes.json
Feature include Learn area nav menu.
=> feat: learn nav area template

components/DocsRoutes.json, pages/docs/routing/introduction.mdx
translate ```/docs/routing/introduction```
=> translate ```/docs/routing/introduction```

pages/learn/foundations/how-nextjs-works/index.mdx
Translate /learn/foundations/how-nextjs-works/index
=> Translate /learn/foundations/how-nextjs-works/index

components/Card.tsx, pages/_app.tsx, pages/docs/basic-features/data-fetching/incremental-static-regeneration.mdx, tailwind.config.js
翻譯 `/docs/basic-features/incremental-static-regeneration` 及新增 `Card` 元件（只是剛好看到好像沒有人做這個元件，所以嘗試做做看，若有問題都可以再討論）
=> Translate `/docs/basic-features/incremental-static-regeneration` & Add Card component

components/Quiz.tsx
fix: fix_Quiz_is_Submitted_also_can_switch_answer
=> fix: fix_Quiz_is_Submitted_also_can_switch_answer

pages/docs/basic-features/data-fetching/client-side.mdx
[SWR 文件](https://swr.vercel.app/docs/revalidation) 內的 focus tracking 給我的感覺有點像是追蹤使用者 tab 上的動態，所以寫了『追蹤使用者動態』。
=> docs/ translate client side data fetching

pages/docs/testing.mdx
=> completed translation

pages/learn/foundations/from-javascript-to-react/adding-interactivity-with-state.mdx, pages/learn/foundations/from-javascript-to-react/building-ui-with-components.mdx, pages/learn/foundations/from-javascript-to-react/displaying-data-with-props.mdx, pages/learn/foundations/from-javascript-to-react/getting-started-with-react.mdx, pages/learn/foundations/from-javascript-to-react/updating-ui-with-javascript.mdx, pages/learn/foundations/how-nextjs-works/buildtime-and-runtime.mdx, pages/learn/foundations/how-nextjs-works/client-and-server.mdx
=> Feat: add quiz to foundations page

pages/learn/foundations/how-nextjs-works/rendering.mdx
/learn/foundations/how-nextjs-works/rendering 完成 Quiz Component
=> /learn/foundations/how-nextjs-works/rendering 完成 Quiz Component

pages/docs/getting-started.mdx
=> feat: translated getting-started

pages/learn/foundations/how-nextjs-works/compiling.mdx, pages/learn/foundations/how-nextjs-works/development-and-production.mdx
20220924_完成初版翻譯_compling 與 development-and-production
=> 20220924_完成初版翻譯_compling 與 development-and-production

components/DocsRoutes.json, pages/docs/basic-features/image-optimization.mdx
完成 Image Optimization 頁面翻譯  (2022/09/25)
=> feat: translate Image Optimization

pages/docs/routing/dynamic-routes.mdx
translated ```/docs/routing/dynamic-routes```
=> translated ```/docs/routing/dynamic-routes```

pages/learn/foundations/how-nextjs-works/minifying.mdx
=> feat: translate minifying

components/LearnRoutes.json, pages/learn/basics/navigate-between-pages/client-side.mdx, pages/learn/basics/navigate-between-pages/index.mdx, pages/learn/basics/navigate-between-pages/link-component.mdx, pages/learn/basics/navigate-between-pages/pages-in-nextjs.mdx, pages/learn/basics/navigate-between-pages/setup.mdx
翻譯 `/learn/basics/navigate-between-pages/index`
=> feat: translate /learn/basics/navigate-between-pages/index

pages/learn/foundations/how-nextjs-works/code-splitting.mdx
Feature includes code-splitting translation.
=> feat: code-splitting translation

pages/learn/basics/dynamic-routes/page-path-external-data.mdx
Feature includes Page Path Depends on External Data translation.
=> feat: Page Path Depends on External Data translation

pages/learn/basics/dynamic-routes/setup.mdx
Feature includes dynamic route's setup page translation.
=> feat: dynamic route's setup page translation

components/LearnRoutes.json, pages/learn/basics/data-fetching/blog-data.mdx, pages/learn/basics/data-fetching/getstaticprops-details.mdx, pages/learn/basics/data-fetching/implement-getstaticprops.mdx, pages/learn/basics/data-fetching/index.mdx, pages/learn/basics/data-fetching/pre-rendering.mdx, pages/learn/basics/data-fetching/request-time.mdx, pages/learn/basics/data-fetching/setup.mdx, pages/learn/basics/data-fetching/two-forms.mdx, pages/learn/basics/data-fetching/with-data.mdx
翻譯 `/learn/basics/data-fetching/index`
=> feat: translate `/learn/basics/data-fetching/index`

components/LearnRoutes.json, package-lock.json, pages/learn/basics/navigate-between-pages/client-side.mdx, pages/learn/basics/navigate-between-pages/link-component.mdx, pages/learn/basics/navigate-between-pages/pages-in-nextjs.mdx, pages/learn/basics/navigate-between-pages/setup.mdx
/learn/basics/navigate-between-pages translate 
1.setup
2.pages-in-nextjs
3.link-component
4. client-side
=> 10/5 navigat-pages

pages/learn/basics/dynamic-routes/dynamic-routes-details.mdx
Feature comprises detail page translation.
=> feat: detail page translation

pages/learn/basics/dynamic-routes/polishing-index-page.mdx
Feature comprises Polish-index page translation.
=> feat: Polish-index page translation

pages/learn/basics/dynamic-routes/polishing-post-page.mdx
Feature comprises Polish-page translation.
=> feat: Polish-page translation

pages/learn/basics/dynamic-routes/render-markdown.mdx
Feature comprises render-markdown page translation.
=> feat: render-markdown page translation

pages/learn/basics/dynamic-routes/implement-getstaticprops.mdx
Feature comprises getstaticprops page translation.
=> feat: getstaticprops page translation

pages/learn/basics/dynamic-routes/implement-getstaticpaths.mdx
Feature comprises getstaticpaths page translation.
=> feat: getstaticpaths page translation

components/LearnRoutes.json, pages/learn/basics/data-fetching/pre-rendering.mdx
翻譯 `/learn/basics/data-fetching/pre-rendering`
=> feat: translate `/learn/basics/data-fetching/pre-rendering`

components/Button.tsx
=> refactor: using next link instead of html a

components/LearnRoutes.json, pages/learn/basics/deploying-nextjs-app/deploy.mdx, pages/learn/basics/deploying-nextjs-app/finally.mdx, pages/learn/basics/deploying-nextjs-app/github.mdx, pages/learn/basics/deploying-nextjs-app/index.mdx, pages/learn/basics/deploying-nextjs-app/other-hosting-options.mdx, pages/learn/basics/deploying-nextjs-app/platform-details.mdx, pages/learn/basics/deploying-nextjs-app/setup.mdx
翻譯 Deploying Your Next.js App index 頁面以及建立頁面檔案
=> docs: translate deploying your nextjs app

pages/learn/basics/data-fetching/pre-rendering.mdx
Edit spelling Chorme change to Chrome.
=> fix: corrected spelling in pre-rendering.mdx

components/Footer.tsx, components/Layout/index.tsx, components/LearnRoutes.json, components/TopNav.tsx, pages/learn/basics/deploying-nextjs-app/github.mdx
1. 翻譯 /github
2. 調整 width css，現在不會有橫向 scrollbar 了！
before:
after:
=> docs: translate deploying nextjs app/GitHub

pages/learn/basics/dynamic-routes/setup.mdx
Change URL /setup to /page-path-external-data
=> fix: corrected URL path

pages/learn/basics/navigate-between-pages/pages-in-nextjs.mdx, pages/learn/foundations/about-nextjs/what-is-nextjs.mdx, pages/learn/foundations/from-javascript-to-react/adding-interactivity-with-state.mdx, pages/learn/foundations/from-javascript-to-react/building-ui-with-components.mdx, pages/learn/foundations/from-javascript-to-react/continue-learning-react.mdx, pages/learn/foundations/from-javascript-to-react/displaying-data-with-props.mdx, pages/learn/foundations/from-javascript-to-react/essential-javascript-react.mdx, pages/learn/foundations/from-javascript-to-react/getting-started-with-react.mdx, pages/learn/foundations/from-javascript-to-react/index.mdx, pages/learn/foundations/from-javascript-to-react/react-core-concepts.mdx, pages/learn/foundations/from-javascript-to-react/updating-ui-with-javascript.mdx, pages/learn/foundations/from-react-to-nextjs/getting-started-with-nextjs.mdx, pages/learn/foundations/from-react-to-nextjs/next-steps.mdx, pages/learn/foundations/how-nextjs-works/buildtime-and-runtime.mdx, pages/learn/foundations/how-nextjs-works/bundling.mdx, pages/learn/foundations/how-nextjs-works/cdns-and-edge.mdx, pages/learn/foundations/how-nextjs-works/client-and-server.mdx, pages/learn/foundations/how-nextjs-works/code-splitting.mdx, pages/learn/foundations/how-nextjs-works/compiling.mdx, pages/learn/foundations/how-nextjs-works/development-and-production.mdx, pages/learn/foundations/how-nextjs-works/minifying.mdx, pages/learn/foundations/how-nextjs-works/next-steps.mdx, pages/learn/foundations/how-nextjs-works/rendering.mdx
新增上一頁和下一頁按鈕在 `learn/foundations` 每一頁
=> feat: `learn/foundations` page add next/front page button

pages/learn/basics/deploying-nextjs-app/other-hosting-options.mdx
=> fix: add spaces between Chinese and English's words
